Fix Go binding compilation error
This code failed to build on Go 1.12 with the error:

`rtmidi.go:75:39: identifier "_Ctype_uint" may conflict with identifiers generated by cgo`

This change seems to be the proper way to convert between C types in cgo and fixes this error.